version: "3.7"

services:

  nginx:
    build:
      context: .docker/nginx
    tty: true
    restart: always
    networks:
      - backend
      - database
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./.docker/nginx/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PHP_HOST=php
      - PHP_PORT=9000
      - DB_HOST=database
      - DB_PORT=3306
    depends_on:
      - database
    command: ["./wait-for-it.sh", "database:3306", "-t=90"]

  php:
    build:
      context: .docker/php-fpm
      args:
        APP_ENVIROMENT: ${APP_ENVIROMENT}
    tty: true
    networks:
      - backend
    ports:
      - 9000
    volumes:
      - "./www:/var/www/html"

  redis:
    image: redis:6-alpine
    ports:
      - 6379
    networks:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123
    networks:
      - database
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

networks:
  backend:
    driver: bridge
  database:
    driver: bridge

volumes:
  dbdata:
    driver: local
    labels:
      mf.project.name: ${COMPOSE_PROJECT_NAME}